site_name: "ms-transactions-channels-capture-gateway"
nav:
  - 'Visão Geral': index.md
  - 'Recursos': pages/recursos.md
  - 'Dependências': pages/dependencias.md
  - 'Começar': pages/comecar.md
  - 'Conteúdo Relacionado': pages/relacionado.md
  - 'Contato': pages/contato.md
plugins:
  - ms-transactions-channels-capture-gateway