spring:
  application:
    name: ms-transactions-channels-capture-gateway


server-thread-pool:
  core-size: ${THREAD_POOL_CORE_SIZE:10}
  max-size: ${THREAD_POOL_MAX_SIZE:30}
  queue-capacity: ${THREAD_POOL_QUEUE_CAPACITY:350000}
  keep_alive_seconds: ${THREAD_POOL_KEEP_ALIVE_SECONDS:10}

tcp:
  port: ${TCP_PORT:9998}
  factory:
    connection:
      backlog: 10000
  message:
    size:
      max: 25000

springdoc:
  packagesToScan: com.picpay.capturechannels, com.picpay.capturechannels.adapter.tcp, com.picpay.capturechanels.core
  swagger-ui:
    title: Swagger Capture Channels
    description: Serviço de captura de canais
    version: 2.1.0

management:
  health:
    diskSpace:
      enabled: false
    probes:
      enabled: true
  endpoints:
    health:
      sensitive: false
    web:
      exposure:
        include: prometheus, health, openapi, swaggerui
      base-path: '/'
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      show-details: always
